//! The Provider artifact and Nix package/catalog generator.
//!
//! `ADR-046-provider-model-and-packaging` work item `ADR046-provider-002`
//! makes the Provider crate layout and the generic Nix Provider
//! package/catalog emitter generated rather than hand-maintained. This module
//! is where that generator lands.
//!
//! What it emits is the frozen shape of a Provider package-catalog entry: the
//! nine field groups the specification's "Package catalog" section enumerates,
//! flattened into the exact field names `nixos-modules/provider-catalog.nix`
//! validates every entry against. The catalog itself is compiled in Nix from
//! `d2b.artifacts.<id>` declarations; only its shape is generated here, so that
//! the module and any later Rust consumer cannot drift apart silently.
//!
//! Three absences in that section are the design rather than gaps, and the
//! generated artifact records them so a later reader does not restore one as a
//! missing feature: selection is by exact digest, so there is no runtime
//! marketplace or download, no PATH or directory discovery, and no `latest` or
//! version-range solving.

use std::{collections::BTreeSet, fs, path::Path, path::PathBuf};

use crate::provider_crate_policy::PROVIDER_MATRIX;

const GENERATED_HEADER: &str = concat!(
    "# Generated by `bazel run //packages/xtask:xtask -- gen-provider-packaging`.\n",
    "# Do not hand-edit: the owner-local drift action compares this\n",
    "# file byte-for-byte against the generator output.\n",
);

/// One field group of a catalog entry, as the specification enumerates them.
struct FieldGroup {
    /// The specification's own bullet text, reproduced as the group comment.
    bullet: &'static str,
    /// The entry fields the bullet names, in the bullet's own order.
    fields: &'static [&'static str],
}

/// The nine field groups of the "Package catalog" section, in its order.
///
/// The order is the specification's and is not a preference: a reader
/// comparing the artifact against the section should be able to walk both top
/// to bottom. The flattened, sorted field list is emitted alongside it, because
/// that is the form a validator wants.
const CATALOG_FIELD_GROUPS: &[FieldGroup] = &[
    FieldGroup {
        bullet: "Provider/package/publisher/version",
        fields: &["providerName", "packageName", "publisher", "version"],
    },
    FieldGroup {
        bullet: "package/executable/manifest/component/descriptor/config digests",
        fields: &[
            "packageDigest",
            "executableDigest",
            "manifestDigest",
            "componentDigest",
            "descriptorDigest",
            "configDigest",
        ],
    },
    FieldGroup {
        bullet: "systems/platform",
        fields: &["systems", "platform"],
    },
    FieldGroup {
        bullet: "API/service compatibility",
        fields: &["apiCompatibility", "serviceCompatibility"],
    },
    FieldGroup {
        bullet: "signature/root epoch/revocation/deny status",
        fields: &["signature", "rootEpoch", "revocationStatus", "denyStatus"],
    },
    FieldGroup {
        bullet: "provenance/SBOM/license/vulnerability evidence",
        fields: &[
            "provenanceEvidence",
            "sbomEvidence",
            "licenseEvidence",
            "vulnerabilityEvidence",
        ],
    },
    FieldGroup {
        bullet: "conformance attestation",
        fields: &["conformanceAttestation"],
    },
    FieldGroup {
        bullet: "support channel",
        fields: &["supportChannel"],
    },
    FieldGroup {
        bullet: "support contact",
        fields: &["supportContact"],
    },
];

/// The subset of entry fields that carry a digest and are therefore the fields
/// exact-digest selection compares. Named separately so the module can require
/// them present and non-empty without re-deriving the set from a name suffix.
const DIGEST_FIELDS: &[&str] = &[
    "componentDigest",
    "configDigest",
    "descriptorDigest",
    "executableDigest",
    "manifestDigest",
    "packageDigest",
];

/// The mechanisms the specification rules out. Emitted so the module can name
/// the rule it is enforcing when it refuses an entry.
const EXCLUDED_MECHANISMS: &[&str] = &[
    "directory-discovery",
    "latest",
    "path-scan",
    "runtime-download",
    "runtime-marketplace",
    "version-range-solving",
];

/// Placement fields emitted by the signed Provider manifest contract.
const PLACEMENT_CONTRACT_FIELDS: &[&str] = &[
    "instanceScope",
    "supportedTargetKinds",
    "targetCapabilities",
    "placementAnchor",
];

/// Shared Host/Guest runtime artifact fields emitted by the signed manifest
/// contract.
const RUNTIME_CONTRACT_FIELDS: &[&str] = &["d2bdDigest", "brokerDigest"];

/// Trust fields that are not part of the historical package-fact bullets but
/// are required when a catalog entry publishes an admission envelope.
const TRUST_CONTRACT_FIELDS: &[&str] = &[
    "trustEpoch",
    "revocationRef",
    "publisherRoot",
    "signatureId",
    "conformanceAttestationDigest",
];

const PROVIDER_ARTIFACT_REQUIRED_FILES: &[&str] = &[
    "share/d2b/provider/provider-manifest.json",
    "share/d2b/provider/provider-manifest.json.sig",
    "share/d2b/provider/config-schema.json",
];

fn nix_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '$' => escaped.push_str("\\$"),
            other => escaped.push(other),
        }
    }
    escaped.push('"');
    escaped
}

fn nix_string_list(values: impl IntoIterator<Item = String>, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let inner = " ".repeat(indent + 2);
    let mut out = String::from("[\n");
    for value in values {
        out.push_str(&format!("{inner}{}\n", nix_string(&value)));
    }
    out.push_str(&format!("{pad}]"));
    out
}

/// Every catalog entry field, flattened and sorted.
fn all_fields() -> Vec<String> {
    let unique: BTreeSet<String> = CATALOG_FIELD_GROUPS
        .iter()
        .flat_map(|group| group.fields.iter().map(|field| (*field).to_owned()))
        .collect();
    unique.into_iter().collect()
}

/// Render the generated catalog-shape module.
fn generated_catalog_shape_module() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str(
        "#\n\
         # The frozen shape of one entry in the offline Provider package\n\
         # catalog, from the \"Package catalog\" section of\n\
         # docs/specs/ADR-046-provider-model-and-packaging.md.\n\
         #\n\
         # Selection is by exact digest. The excluded mechanisms below are\n\
         # ruled out by that section and are absent by design, not by\n\
         # omission.\n",
    );
    out.push_str("{\n");

    out.push_str("  # Entry field groups, in the specification's own order.\n");
    out.push_str("  fieldGroups = [\n");
    for group in CATALOG_FIELD_GROUPS {
        out.push_str("    {\n");
        out.push_str(&format!("      bullet = {};\n", nix_string(group.bullet)));
        out.push_str(&format!(
            "      fields = {};\n",
            nix_string_list(group.fields.iter().map(|field| (*field).to_owned()), 6)
        ));
        out.push_str("    }\n");
    }
    out.push_str("  ];\n\n");

    out.push_str("  # Every entry field, flattened and sorted. A catalog entry\n");
    out.push_str("  # carries exactly these attributes.\n");
    out.push_str(&format!(
        "  fields = {};\n\n",
        nix_string_list(all_fields(), 2)
    ));

    out.push_str("  # The fields exact-digest selection compares.\n");
    out.push_str(&format!(
        "  digestFields = {};\n\n",
        nix_string_list(DIGEST_FIELDS.iter().map(|field| (*field).to_owned()), 2)
    ));

    out.push_str("  # Ruled out by the specification; recorded so a reader does\n");
    out.push_str("  # not restore one as a missing feature.\n");
    out.push_str(&format!(
        "  excludedMechanisms = {};\n",
        nix_string_list(
            EXCLUDED_MECHANISMS.iter().map(|value| (*value).to_owned()),
            2
        )
    ));

    out.push_str("\n  # Signed placement-contract fields carried by the Provider\n");
    out.push_str("  # manifest and consumed by Core admission.\n");
    out.push_str(&format!(
        "  placementContractFields = {};\n",
        nix_string_list(
            PLACEMENT_CONTRACT_FIELDS
                .iter()
                .map(|field| (*field).to_owned()),
            2
        )
    ));
    out.push_str("\n  # Signed shared daemon and broker artifact fields.\n");
    out.push_str(&format!(
        "  runtimeContractFields = {};\n",
        nix_string_list(
            RUNTIME_CONTRACT_FIELDS
                .iter()
                .map(|field| (*field).to_owned()),
            2
        )
    ));

    out.push_str("\n  # Additional trust-envelope fields checked when published.\n");
    out.push_str(&format!(
        "  trustFields = {};\n",
        nix_string_list(
            TRUST_CONTRACT_FIELDS
                .iter()
                .map(|field| (*field).to_owned()),
            2
        )
    ));

    out.push_str("\n  # The immutable Provider output layout.\n");
    out.push_str("  artifactLayout = {\n");
    out.push_str("    executableDirectory = \"bin\";\n");
    out.push_str("    metadataDirectory = \"share/d2b/provider\";\n");
    out.push_str("    multiBinary = true;\n");
    out.push_str(&format!(
        "    requiredFiles = {};\n",
        nix_string_list(
            PROVIDER_ARTIFACT_REQUIRED_FILES
                .iter()
                .map(|path| (*path).to_owned()),
            4
        )
    ));
    out.push_str("    noBinaryBootstrapProvider = \"system-core\";\n");
    out.push_str("    fixedBootstrapProviders = [\n");
    for row in PROVIDER_MATRIX.iter().filter(|row| row.bootstrap) {
        out.push_str(&format!("      {}\n", nix_string(row.identity)));
    }
    out.push_str("    ];\n");
    out.push_str("  };\n");

    out.push_str("\n  # The closed Provider identity/package/dossier/test matrix.\n");
    out.push_str("  providerMatrix = [\n");
    for row in PROVIDER_MATRIX {
        out.push_str("    {\n");
        out.push_str(&format!(
            "      provider = {};\n",
            nix_string(row.identity)
        ));
        out.push_str(&format!(
            "      package = {};\n",
            nix_string(row.crate_name)
        ));
        out.push_str(&format!(
            "      source = {};\n",
            nix_string(row.source_path)
        ));
        out.push_str(&format!(
            "      test = {};\n",
            nix_string(row.test_path)
        ));
        out.push_str(&format!(
            "      dossier = {};\n",
            nix_string(row.dossier_path)
        ));
        out.push_str(&format!(
            "      bazelTarget = {};\n",
            nix_string(row.bazel_target)
        ));
        out.push_str(&format!("      unit = {};\n", nix_string(row.unit)));
        out.push_str(&format!("      bootstrap = {};\n", row.bootstrap));
        out.push_str("    }\n");
    }
    out.push_str("  ];\n\n");

    out.push_str("  providerIds = [\n");
    for row in PROVIDER_MATRIX {
        out.push_str(&format!("    {}\n", nix_string(row.identity)));
    }
    out.push_str("  ];\n\n");

    out.push_str("  fixedBootstrapProviderIds = [\n");
    for row in PROVIDER_MATRIX.iter().filter(|row| row.bootstrap) {
        out.push_str(&format!("    {}\n", nix_string(row.identity)));
    }
    out.push_str("  ];\n");

    out.push_str("}\n");
    out
}

/// Generate the Provider catalog shape and the closed Provider matrix.
///
/// Returns the paths written. An empty success is deliberately not a possible
/// return: a caller comparing a generator's output against the committed tree
/// must not be able to read "wrote nothing" as "everything is current".
pub fn gen_provider_packaging(
    repo_root: &Path,
) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let out_dir = repo_root.join("nixos-modules/generated");
    fs::create_dir_all(&out_dir)?;

    let path = out_dir.join("provider-catalog-shape.nix");
    fs::write(&path, generated_catalog_shape_module())?;

    let written = vec![path];
    if written.is_empty() {
        return Err("gen-provider-packaging wrote no artifact; refusing to report success".into());
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_specification_bullet_has_at_least_one_field() {
        assert_eq!(
            CATALOG_FIELD_GROUPS.len(),
            9,
            "the Package catalog section enumerates nine bullets"
        );
        for group in CATALOG_FIELD_GROUPS {
            assert!(
                !group.fields.is_empty(),
                "bullet '{}' names no field",
                group.bullet
            );
        }
    }

    #[test]
    fn no_field_is_declared_by_two_groups() {
        let mut seen = BTreeSet::new();
        for group in CATALOG_FIELD_GROUPS {
            for field in group.fields {
                assert!(
                    seen.insert(*field),
                    "field '{field}' is declared by more than one group"
                );
            }
        }
        assert_eq!(seen.len(), all_fields().len());
    }

    #[test]
    fn the_digest_fields_are_a_sorted_subset_of_the_entry_fields() {
        let fields = all_fields();
        let mut sorted = DIGEST_FIELDS.to_vec();
        sorted.sort_unstable();
        assert_eq!(DIGEST_FIELDS, sorted.as_slice(), "digest fields are sorted");
        for digest in DIGEST_FIELDS {
            assert!(
                fields.iter().any(|field| field == digest),
                "digest field '{digest}' is not an entry field"
            );
        }
    }

    #[test]
    fn the_excluded_mechanisms_are_sorted_and_unique() {
        let mut sorted = EXCLUDED_MECHANISMS.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(EXCLUDED_MECHANISMS, sorted.as_slice());
    }

    #[test]
    fn signed_contract_field_groups_are_closed_and_deterministic() {
        assert_eq!(
            PLACEMENT_CONTRACT_FIELDS,
            &[
                "instanceScope",
                "supportedTargetKinds",
                "targetCapabilities",
                "placementAnchor",
            ]
        );
        assert_eq!(RUNTIME_CONTRACT_FIELDS, &["d2bdDigest", "brokerDigest"]);
    }

    #[test]
    fn the_provider_matrix_and_artifact_layout_are_closed() {
        assert_eq!(PROVIDER_MATRIX.len(), 27);
        assert_eq!(
            PROVIDER_ARTIFACT_REQUIRED_FILES,
            &[
                "share/d2b/provider/provider-manifest.json",
                "share/d2b/provider/provider-manifest.json.sig",
                "share/d2b/provider/config-schema.json",
            ]
        );
        assert!(PROVIDER_MATRIX.iter().any(|row| row.identity == "system-core"));
        assert!(PROVIDER_MATRIX.iter().any(|row| row.identity == "system-minijail"));
        assert_eq!(
            TRUST_CONTRACT_FIELDS,
            &[
                "trustEpoch",
                "revocationRef",
                "publisherRoot",
                "signatureId",
                "conformanceAttestationDigest",
            ]
        );
    }

    #[test]
    fn generated_provider_matrix_contains_every_closed_identity() {
        let rendered = generated_catalog_shape_module();
        for row in PROVIDER_MATRIX {
            assert!(rendered.contains(&format!("provider = \"{}\";", row.identity)));
            assert!(rendered.contains(&format!("package = \"{}\";", row.crate_name)));
            assert!(rendered.contains(row.bazel_target));
        }
        assert!(rendered.contains("fixedBootstrapProviderIds"));
    }

    #[test]
    fn the_rendered_module_is_byte_identical_across_repeated_renders() {
        let first = generated_catalog_shape_module();
        for _ in 0..8 {
            assert_eq!(first, generated_catalog_shape_module());
        }
    }

    #[test]
    fn the_rendered_module_contains_no_non_ascii_dash() {
        let banned = [
            '\u{2010}', '\u{2011}', '\u{2012}', '\u{2013}', '\u{2014}', '\u{2015}', '\u{2212}',
            '\u{fe58}', '\u{ff0d}',
        ];
        let rendered = generated_catalog_shape_module();
        for character in banned {
            assert!(
                !rendered.contains(character),
                "generated artifact must not contain U+{:04X}",
                character as u32
            );
        }
    }

    /// One catalog field and the exact Rust contract field expressing the
    /// same concept, as `(catalog field, contract struct, contract field)`.
    ///
    /// The mapping is written out rather than derived. The two artifacts
    /// were authored independently from the same specification bullets,
    /// which name concepts and not identifiers, so the same concept is
    /// legitimately spelled differently on each side. Normalising the two
    /// spellings together - lowercasing, dropping separators, matching on a
    /// shared prefix - would make a genuinely wrong name look right, which
    /// is exactly the drift this check exists to catch.
    const CATALOG_TO_CONTRACT: &[(&str, &str, &str)] = &[
        ("providerName", "ProviderManifest", "artifact_id"),
        ("publisher", "TrustEvidence", "publisher"),
        ("executableDigest", "ArtifactDigestSet", "executable"),
        ("configDigest", "ArtifactDigestSet", "config"),
        ("apiCompatibility", "CompatibilityRange", "api_major"),
        ("apiCompatibility", "CompatibilityRange", "api_minor"),
        (
            "serviceCompatibility",
            "CompatibilityRange",
            "descriptor_fingerprint",
        ),
        ("signature", "TrustEvidence", "signature"),
        ("rootEpoch", "TrustEvidence", "root_epoch"),
        ("revocationStatus", "TrustEvidence", "revocation"),
        ("denyStatus", "TrustEvidence", "emergency_deny"),
        ("provenanceEvidence", "TrustEvidence", "provenance"),
        ("sbomEvidence", "TrustEvidence", "sbom"),
        ("licenseEvidence", "TrustEvidence", "license"),
        ("vulnerabilityEvidence", "TrustEvidence", "vulnerability"),
        ("conformanceAttestation", "TrustEvidence", "conformance"),
        ("supportChannel", "TrustEvidence", "support_channel"),
    ];

    /// Catalog fields with no counterpart in the Rust contract.
    ///
    /// This is a recorded finding, not an accepted equivalence. Each entry
    /// is a catalog fact the specification's "Package catalog" bullets name
    /// and the contract does not carry. The list is pinned exactly, so
    /// closing one of these on either side fails this test and forces the
    /// entry to be removed alongside the fix.
    const CATALOG_FIELDS_WITHOUT_A_CONTRACT_FIELD: &[&str] = &[
        "componentDigest",
        "descriptorDigest",
        "manifestDigest",
        "packageDigest",
        "packageName",
        "platform",
        "supportContact",
        "systems",
        "version",
    ];

    /// Contract fields on the catalog-fact carriers with no counterpart in
    /// the catalog shape, pinned on the same terms as the list above.
    ///
    /// `ArtifactDigestSet::schema` and `ArtifactDigestSet::service` are the
    /// contract-only half of the digest split: the catalog carries package and
    /// manifest digests because those values cannot be self-referential in the
    /// signed manifest, while the contract carries exported schema and service
    /// surface digests. These are different facts, not alternate spellings.
    const CONTRACT_FIELDS_WITHOUT_A_CATALOG_FIELD: &[(&str, &str)] = &[
        ("ArtifactDigestSet", "schema"),
        ("ArtifactDigestSet", "service"),
        ("TrustEvidence", "publisher_trusted"),
    ];

    /// The contract structs whose every field must be accounted for.
    ///
    /// These two carry the leaf catalog facts. `ProviderManifest` and
    /// `CompatibilityRange` are read for the fields the mapping names but
    /// are not held to exhaustiveness: their remaining fields are the
    /// manifest's composite sub-structures and the state-schema version,
    /// which the catalog entry does not restate.
    const EXHAUSTIVE_CONTRACT_STRUCTS: &[&str] = &["ArtifactDigestSet", "TrustEvidence"];

    /// The declared field names of one struct in the Provider contract.
    ///
    /// The contract source is read from disk rather than transcribed here,
    /// so a rename on that side is observed rather than assumed.
    fn contract_struct_fields(source: &str, struct_name: &str) -> Vec<String> {
        let header = format!("pub struct {struct_name} {{");
        let body = source
            .split_once(&header)
            .unwrap_or_else(|| panic!("{struct_name} is not declared as a braced struct"))
            .1;
        let mut fields = Vec::new();
        for line in body.lines() {
            let line = line.trim();
            if line == "}" {
                return fields;
            }
            if line.is_empty() || line.starts_with('#') || line.starts_with("//") {
                continue;
            }
            let Some((name, _)) = line.split_once(':') else {
                continue;
            };
            let name = name.trim().trim_start_matches("pub ").trim();
            if !name.is_empty()
                && name
                    .chars()
                    .all(|character| character.is_ascii_lowercase() || character == '_')
            {
                fields.push(name.to_owned());
            }
        }
        panic!("{struct_name} has no closing brace at column zero");
    }

    #[test]
    fn the_catalog_shape_and_the_provider_contract_describe_the_same_fields() {
        let contract_path = crate::repo_root()
            .expect("repository root")
            .join("packages/d2b-contracts-provider/src/v3/provider.rs")
            .canonicalize()
            .expect("the Provider contract source is in the tree");
        let source = fs::read_to_string(&contract_path).expect("the contract source is readable");

        // Every mapped contract field is really declared by that struct.
        for (catalog_field, struct_name, contract_field) in CATALOG_TO_CONTRACT {
            let declared = contract_struct_fields(&source, struct_name);
            assert!(
                declared.iter().any(|field| field == contract_field),
                "catalog field '{catalog_field}' maps to {struct_name}::{contract_field}, \
                 which that struct no longer declares"
            );
        }

        // Every catalog field is either mapped or a recorded divergence,
        // and the two sets partition the catalog exactly.
        let mapped_catalog: BTreeSet<&str> = CATALOG_TO_CONTRACT
            .iter()
            .map(|(catalog_field, _, _)| *catalog_field)
            .collect();
        let unmapped_catalog: BTreeSet<&str> = CATALOG_FIELDS_WITHOUT_A_CONTRACT_FIELD
            .iter()
            .copied()
            .collect();
        assert!(
            mapped_catalog.is_disjoint(&unmapped_catalog),
            "a catalog field is both mapped and recorded as unmapped"
        );
        let accounted: BTreeSet<&str> = mapped_catalog.union(&unmapped_catalog).copied().collect();
        let actual: BTreeSet<String> = all_fields().into_iter().collect();
        let actual_borrowed: BTreeSet<&str> = actual.iter().map(String::as_str).collect();
        assert_eq!(
            accounted, actual_borrowed,
            "the catalog fields and the parity mapping have diverged"
        );

        // Every field of the catalog-fact carriers is either mapped or a
        // recorded divergence.
        let unmapped_contract: BTreeSet<(&str, &str)> = CONTRACT_FIELDS_WITHOUT_A_CATALOG_FIELD
            .iter()
            .copied()
            .collect();
        for struct_name in EXHAUSTIVE_CONTRACT_STRUCTS {
            for field in contract_struct_fields(&source, struct_name) {
                let mapped = CATALOG_TO_CONTRACT
                    .iter()
                    .any(|(_, owner, name)| owner == struct_name && *name == field);
                let recorded = unmapped_contract.contains(&(struct_name, field.as_str()));
                assert!(
                    mapped ^ recorded,
                    "{struct_name}::{field} is neither mapped to a catalog field nor \
                     recorded as having no catalog counterpart, or is both"
                );
            }
        }

        // The recorded contract-side divergences still exist; a resolved
        // one must be struck from the list rather than left behind.
        for (struct_name, field) in CONTRACT_FIELDS_WITHOUT_A_CATALOG_FIELD {
            assert!(
                contract_struct_fields(&source, struct_name)
                    .iter()
                    .any(|declared| declared == field),
                "{struct_name}::{field} is recorded as having no catalog counterpart \
                 but is no longer declared"
            );
        }

        // Package and manifest digests remain catalog-only because the signed
        // manifest cannot carry values computed over itself or its package.
        let digest_fields = contract_struct_fields(&source, "ArtifactDigestSet");
        assert_eq!(
            digest_fields.len(),
            4,
            "the signed manifest carries only executable, config, schema, and service digests"
        );
    }

    #[test]
    fn the_generator_never_reports_an_empty_success() {
        // The contract the stub established and this implementation keeps: a
        // successful return names at least one written path, so a drift gate
        // cannot read silence as currency.
        let dir =
            std::env::temp_dir().join(format!("d2b-provider-packaging-gen-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        let written = gen_provider_packaging(&dir).expect("generation succeeds");
        assert!(!written.is_empty());
        for path in &written {
            assert!(path.is_file(), "{} was not written", path.display());
        }
        let _ = fs::remove_dir_all(&dir);
    }
}
