//! Generated Provider service server lifecycle.
//!
//! V3 service stubs are generated by the service-contract owner. This module
//! owns the stable server-side lifecycle around those stubs: one bounded
//! adapter, an accepting flag, and a drain waiter that cannot miss the final
//! in-flight release.

use std::{
    fmt,
    sync::{
        Arc,
        atomic::{AtomicBool, AtomicUsize, Ordering},
    },
    time::Duration,
};

use d2b_contracts_provider::v3::SpecifiedProviderMethod;
use d2b_contracts_resource::v3::identity::ServiceName;
use d2b_contracts_resource::v3::{
    CanonicalJsonObject, ResourceRef, execution_policy::BoundedToken,
};
use d2b_contracts_zone_session::v3::{component_session::RequestId, zone_routing::ZonePath};
use d2b_session::{AuthenticatedSessionRouteBinding, Cancellation, ComponentSessionDriver};
use tokio::sync::Notify;

use crate::{ProviderAgentAdapter, ProviderFrameCodec, ProviderService, ProviderToolkitError};

/// Maximum calls a generated service server may drain at once.
pub const MAX_SERVER_IN_FLIGHT: usize = 64;

/// A generated v3 service advertisement.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedServiceDescriptor {
    package: ServiceName,
    methods: Vec<SpecifiedProviderMethod>,
}

impl GeneratedServiceDescriptor {
    /// Construct the closed Provider service advertisement.
    pub fn provider() -> Self {
        Self {
            package: ServiceName::parse("d2b.provider.v3").expect("closed service package"),
            methods: vec![
                SpecifiedProviderMethod::OpenTransport,
                SpecifiedProviderMethod::CloseTransport,
                SpecifiedProviderMethod::ObserveTransport,
                SpecifiedProviderMethod::AssessUpdate,
                SpecifiedProviderMethod::PlanUpgrade,
                SpecifiedProviderMethod::ExecuteUpgrade,
            ],
        }
    }

    /// Borrow the generated service package.
    pub const fn package(&self) -> &ServiceName {
        &self.package
    }

    /// Borrow the closed generated method list.
    pub fn methods(&self) -> &[SpecifiedProviderMethod] {
        &self.methods
    }
}

/// Why a generated server refused a request or could not drain.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServerError {
    /// The server has stopped accepting new calls.
    NotAccepting,
    /// The server's fixed in-flight bound is exhausted.
    InFlightLimit,
    /// The ComponentSession frame or adapter rejected a request.
    Dispatch(ProviderToolkitError),
}

impl fmt::Display for ServerError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::NotAccepting => "provider-server-not-accepting",
            Self::InFlightLimit => "provider-server-in-flight-limit",
            Self::Dispatch(_) => "provider-server-dispatch-failed",
        })
    }
}

impl std::error::Error for ServerError {}

/// A server-side in-flight request reservation.
///
/// Dropping the reservation is the only release path. It is deliberately not
/// cloneable, so a request cannot release its slot more than once.
pub struct ServerRequestPermit {
    state: Arc<ServerState>,
}

impl fmt::Debug for ServerRequestPermit {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("ServerRequestPermit(<redacted>)")
    }
}

impl Drop for ServerRequestPermit {
    fn drop(&mut self) {
        if self.state.in_flight.fetch_sub(1, Ordering::AcqRel) == 1 {
            self.state.idle.notify_waiters();
        }
    }
}

struct ServerState {
    accepting: AtomicBool,
    in_flight: AtomicUsize,
    idle: Notify,
}

impl ServerState {
    fn new() -> Self {
        Self {
            accepting: AtomicBool::new(true),
            in_flight: AtomicUsize::new(0),
            idle: Notify::new(),
        }
    }
}

/// The lifecycle wrapper around one generated Provider service.
pub struct GeneratedProviderServiceServer<S> {
    adapter: ProviderAgentAdapter<S>,
    state: Arc<ServerState>,
    generated: GeneratedServiceDescriptor,
}

impl<S> fmt::Debug for GeneratedProviderServiceServer<S> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GeneratedProviderServiceServer")
            .field("package", &self.generated.package())
            .field("method_count", &self.generated.methods().len())
            .field("accepting", &self.is_accepting())
            .field("in_flight", &self.in_flight())
            .finish_non_exhaustive()
    }
}

impl<S> GeneratedProviderServiceServer<S> {
    /// Construct a server around one Provider implementation.
    pub fn new(service: S) -> Self {
        Self {
            adapter: ProviderAgentAdapter::new(service),
            state: Arc::new(ServerState::new()),
            generated: GeneratedServiceDescriptor::provider(),
        }
    }

    /// Borrow the bounded Provider adapter.
    pub const fn adapter(&self) -> &ProviderAgentAdapter<S> {
        &self.adapter
    }

    /// Bind the generated server to one authenticated controller route.
    pub fn bind_authenticated_route(
        &self,
        route: AuthenticatedSessionRouteBinding,
    ) -> Result<(), ProviderToolkitError> {
        if route.service() != self.generated.package() {
            return Err(ProviderToolkitError::SessionUnauthenticated);
        }
        self.adapter.bind_authenticated_route(route)
    }

    /// Borrow the generated service descriptor.
    pub const fn generated_service(&self) -> &GeneratedServiceDescriptor {
        &self.generated
    }

    /// Return whether new requests are accepted.
    pub fn is_accepting(&self) -> bool {
        self.state.accepting.load(Ordering::Acquire)
    }

    /// Return the number of currently admitted server requests.
    pub fn in_flight(&self) -> usize {
        self.state.in_flight.load(Ordering::Acquire)
    }

    /// Reserve a server request slot.
    pub fn admit_request(&self) -> Result<ServerRequestPermit, ServerError> {
        if !self.is_accepting() {
            return Err(ServerError::NotAccepting);
        }
        let mut current = self.state.in_flight.load(Ordering::Acquire);
        loop {
            if current >= MAX_SERVER_IN_FLIGHT {
                return Err(ServerError::InFlightLimit);
            }
            match self.state.in_flight.compare_exchange_weak(
                current,
                current + 1,
                Ordering::AcqRel,
                Ordering::Acquire,
            ) {
                Ok(_) => break,
                Err(observed) => current = observed,
            }
        }
        if !self.is_accepting() {
            if self.state.in_flight.fetch_sub(1, Ordering::AcqRel) == 1 {
                self.state.idle.notify_waiters();
            }
            return Err(ServerError::NotAccepting);
        }
        Ok(ServerRequestPermit {
            state: Arc::clone(&self.state),
        })
    }

    /// Stop admitting requests and wait for all admitted requests to release.
    ///
    /// The `Notify` future is armed before the in-flight count is checked,
    /// closing the final-permit check/await race.
    pub async fn shutdown(&self, timeout: Duration) -> bool {
        self.state.accepting.store(false, Ordering::Release);
        tokio::time::timeout(timeout, async {
            loop {
                let notified = self.state.idle.notified();
                tokio::pin!(notified);
                notified.as_mut().enable();
                if self.in_flight() == 0 {
                    break;
                }
                notified.as_mut().await;
            }
        })
        .await
        .is_ok()
    }
}

impl<S> GeneratedProviderServiceServer<S>
where
    S: ProviderService,
{
    /// Dispatch one generated-service request under server admission.
    pub fn dispatch(
        &self,
        zone: ZonePath,
        provider_ref: ResourceRef,
        method: BoundedToken,
        payload: CanonicalJsonObject,
    ) -> Result<CanonicalJsonObject, ServerError> {
        let _permit = self.admit_request()?;
        self.adapter
            .dispatch(zone, provider_ref, method, payload)
            .map_err(ServerError::Dispatch)
    }

    /// Serve frames from an authenticated ComponentSession.
    ///
    /// The server must first be bound with [`Self::bind_authenticated_route`];
    /// an unbound server refuses the loop before reading transport data.
    pub async fn serve_component_session<D, C>(
        &self,
        driver: &D,
        codec: &C,
        cancellation: Cancellation,
    ) -> Result<(), ServerError>
    where
        D: ComponentSessionDriver,
        C: ProviderFrameCodec,
    {
        let _permit = self.admit_request()?;
        self.adapter
            .serve_component_session(driver, codec, cancellation)
            .await
            .map_err(ServerError::Dispatch)
    }

    /// Return the generated service metadata as a one-element list.
    ///
    /// The list shape mirrors the generated-service registration boundary
    /// while keeping service stubs owned by the v3 contract generator.
    pub fn generated_services(&self) -> Vec<GeneratedServiceDescriptor> {
        vec![self.generated.clone()]
    }

    /// Encode a response correlation without exposing request contents.
    pub fn response_request_id<'a>(&self, request_id: &'a RequestId) -> &'a RequestId {
        request_id
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{FakeProvider, Fixture};
    use d2b_provider::ProviderClass;

    #[tokio::test]
    async fn shutdown_drains_an_admitted_request_before_reporting_idle() {
        let fixture = Fixture::new(ProviderClass::Runtime, 0).expect("fixture");
        let server = GeneratedProviderServiceServer::new(FakeProvider::new(fixture));
        let permit = server.admit_request().expect("request permit");
        let drain = server.shutdown(Duration::from_millis(1)).await;
        assert!(!drain);
        assert_eq!(server.in_flight(), 1);
        drop(permit);
        assert!(server.shutdown(Duration::from_millis(100)).await);
        assert!(!server.is_accepting());
        assert_eq!(
            server
                .admit_request()
                .expect_err("retired server refuses new requests"),
            ServerError::NotAccepting
        );
    }

    #[test]
    fn generated_server_admits_and_dispatches_one_closed_method() {
        let fixture = Fixture::new(ProviderClass::Runtime, 0).expect("fixture");
        let provider_ref = fixture.descriptor.provider_ref().clone();
        let server = GeneratedProviderServiceServer::new(FakeProvider::new(fixture));
        let response = server
            .dispatch(
                ZonePath::local_root(),
                provider_ref,
                BoundedToken::parse("health").expect("method"),
                CanonicalJsonObject::empty(),
            )
            .expect("dispatch");
        assert!(response.get("state").is_some());
        assert_eq!(server.generated_services().len(), 1);
    }

    #[test]
    fn generated_server_requires_an_authenticated_controller_route_for_session_serving() {
        let fixture = Fixture::new(ProviderClass::Runtime, 0).expect("fixture");
        let server = GeneratedProviderServiceServer::new(FakeProvider::new(fixture.clone()));
        let route = AuthenticatedSessionRouteBinding::for_test(
            Some(fixture.descriptor.provider_ref().clone()),
            "d2b.provider.v3",
            1,
            Some(1),
            Some(1),
        );
        assert!(server.bind_authenticated_route(route).is_ok());
        assert!(server.adapter().has_authenticated_route());

        let wrong_service = AuthenticatedSessionRouteBinding::for_test(
            Some(fixture.descriptor.provider_ref().clone()),
            "d2b.other.v3",
            1,
            Some(1),
            Some(1),
        );
        assert_eq!(
            server.bind_authenticated_route(wrong_service),
            Err(ProviderToolkitError::SessionUnauthenticated)
        );
    }
}
